name: Build and publish Docker image

on: [push]

env:
  IMAGE_NAME: hello-world
  IMAGE_ID: "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}"
  IMAGE_TAG: "${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag image

      - name: Log into registry
        run: echo "${{ github.token }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

      - name: Push image
        run: |
          set -o errexit -o nounset -o pipefail
          docker tag image "$IMAGE_ID:$IMAGE_TAG"
          docker push "$IMAGE_ID:$IMAGE_TAG"

  update-infrastructure:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: '${{ github.repository }}-infrastructure-staging'

      - name: Patch Kubernetes manifest
        run: |
          set -o errexit -o nounset -o pipefail
          touch kustomization.yaml
          kustomize edit add resource manifest.yaml
          kustomize edit set image "$IMAGE_ID:$IMAGE_TAG"
          kustomize build -o manifest.yaml
