name: Staging

on: [push]

env:
  REGISTRY: "docker.pkg.github.com/${{ github.repository }}"
  IMAGE_NAME: "hello-world"
  IMAGE_TAG: "${{ github.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag image

      - name: Log into registry
        run: docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin <<< "${{ github.token }}"

      - name: Push image
        run: |
          set -o errexit -o nounset -o pipefail
          docker tag image "$REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          docker push "$REGISTRY/$IMAGE_NAME:$IMAGE_TAG"

  update-infrastructure:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == refs/heads/master
    env:
      KUSTOMIZE_VERSION: v3.5.4
    steps:
      - uses: actions/checkout@v2
        with:
          path: source

      - uses: actions/checkout@v2
        with:
          path: infra-staging
          repository: "${{ github.repository }}-infrastructure-staging"
          ssh-key: "${{ secrets.STAGING_SSH_KEY }}"

      - uses: ./source/.github/actions/install-kustomize

      - name: Patch Kubernetes manifest
        run: |
          set -o errexit -o nounset -o pipefail
          cd source/infra
          kustomize edit set image "$IMAGE_NAME=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          kustomize build -o "$GITHUB_WORKSPACE/infra-staging/manifest.yaml"

      - name: Commit and push patched manifest
        run: |
          AUTHOR_NAME="$(git -C source show -s --format='%an')"
          AUTHOR_EMAIL="$(git -C source show -s --format='%ae')"
          cd infra-staging
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          git commit manifest.yaml -m "Update configuration for $IMAGE_TAG"
          git push origin master
